default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: protospace_39129_development


  <<: *default
  database: protospace_39129_test

production:
  <<: *default
  database: protospace_39129_production
  username: protospace_39129
  password: <%= ENV['PROTOSPACE_39129_DATABASE_PASSWORD'] %>

